Steam 863/planned treatment phase viz
mcode/rttd-summary-webapp pull request #12
Opened 2022-04-26 18:39 UTC by Dtphelan1

Adds mapping and visualization of PlannedTreatmentPhase profiled ServiceRequest resources based on the IG [here](https://build.fhir.org/ig/HL7/codex-radiation-therapy/StructureDefinition-codexrt-radiotherapy-planned-course.html).

A few other small changes: 
- Change the name of `mapPhase` to `mapTreatedPhase`, more closely aligning with the profile name;
- Move all profile-specific visualizers into a nested directory for better organization of files; I was getting a bit overwhelmed scrolling through a list of 15+ files to find the correct one in the DataView file, and this segments the generic viewer components from the business-logic specific profileVisualizers. 
- Move the iterate-over-mapped-data logic from the DataView to the TreatmentPhaseTable component; the DataView component shouldn't need to to know anything about how the treatmentPhaseTable data is organized.

2022-04-27 19:30 UTC, julianxcarter requested changes
This looks good and works well! I had two comments, one of which I couldn't actually write as part of the review:

Do we think we should remove `Patient-XRTS-01` and `Patient-XRTS-02` as default queries? They seem redundant now that we have the more coplete examples.

2022-04-27 19:30 UTC, julianxcarter commented on src/lib/mappingUtils.js
> +    output["Techniques"] = technique ? technique.display : undefined;
I think it'd be best to alter the above fhirpath to return the `technique.display` value directly, just to be sure that nothing breaks down if the display isn't populated. Similar to what you're doing with the `Modalities` fetching.

2022-04-27 19:51 UTC, Dtphelan1 commented on src/lib/mappingUtils.js
> +    output["Techniques"] = technique ? technique.display : undefined;
Completely agree. This is what happens when someone blindly copy and pastes from previous examples. I'll correct that here and from the source

2022-04-27 19:53 UTC, Dtphelan1 commented
> Do we think we should remove Patient-XRTS-01 and Patient-XRTS-02 as default queries? They seem redundant now that we have the more coplete examples.

I think actually once we add the missing-data sections, they will be useful patients to illustrate what gaps look like. I do agree that they're not the gold-source patients that we used to think of them as. Thoughts on relegating them to the bottom of the ID list, so they're not the first thing you have to see?

2022-04-27 19:55 UTC, julianxcarter commented
> I think actually once we add the missing-data sections, they will be useful patients to illustrate what gaps look like. I do agree that they're not the gold-source patients that we used to think of them as. Thoughts on relegating them to the bottom of the ID list, so they're not the first thing you have to see?

That's a great point and I hadn't thought of that! I do think I'd prefer them being at the bottom of the list.

2022-04-28 13:36 UTC, julianxcarter approved these changes

2022-04-28 13:37 UTC, merged